/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiders;

import java.awt.TrayIcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sakkas
 */
public class DepartmentsGUI extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentsGUI
     */
    public DepartmentsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListDepartments = new javax.swing.JList<>();
        jTextFieldDepName = new javax.swing.JTextField();
        jButtonDepAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(jListDepartments);

        jButtonDepAdd.setText("Ekle");
        jButtonDepAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDepAddMouseClicked(evt);
            }
        });

        jButtonDelete.setText("Sil");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDepAdd)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDepAdd))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButtonDelete)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillDepartmentsjList()
    {
        try {
            
            DefaultListModel<Item> model = new DefaultListModel();
            String connection = "jdbc:hsqldb:file:db/Faculty";
            String sql = "SELECT * FROM TBLDEPARTMENT";
            DBHandler db = new DBHandler(connection);
            ResultSet rs = db.executeQuery(sql);
            while(rs.next())
            {
                model.addElement(new Item(rs.getInt("DEPID"),rs.getString("DEPAD")));
            }
            jListDepartments.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(DepartmentsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fillDepartmentsjList();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonDepAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDepAddMouseClicked
        try {
            String connection = "jdbc:hsqldb:file:db/Faculty";
            String sql = "SELECT COUNT(*) FROM TBLDEPARTMENT WHERE DEPAD = '" + jTextFieldDepName.getText() +"'" ;
            System.out.println(sql);
            DBHandler db = new DBHandler(connection);
            
            if(jTextFieldDepName.getText().isEmpty())
                JOptionPane.showMessageDialog(null, "Bölüm adı boş olamaz");
            else
            {
                ResultSet rs = db.executeQuery(sql);
                int count = 0;
                while(rs.next())
                    count = rs.getInt(1);
                if(count > 0)
                    JOptionPane.showMessageDialog(null, "Aynı isimde bir bölüm var");
                else
                {
                    sql = "INSERT INTO TBLDEPARTMENT( DEPAD ) VALUES ('" +jTextFieldDepName.getText()  + "')";
                    db.executeNonQuery(sql);
                    fillDepartmentsjList();
                    
                }
                    
            }
        } catch (SQLException ex) {
            Logger.getLogger(DepartmentsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDepAddMouseClicked

    private void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseClicked
        Item item = jListDepartments.getSelectedValue();
        if(item == null)
            JOptionPane.showMessageDialog(null, "Silmek için bir bölüm seçiniz");
        else
        {
            try {
                String connection = "jdbc:hsqldb:file:db/Faculty";
                String sql = "DELETE FROM TBLDEPARTMENT WHERE DEPID=" + item.getId();
                System.out.println(sql);
                DBHandler db = new DBHandler(connection);
                
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null,"Silmek istediğinize emin misiniz?", "Uyarı", dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION)
                {
                    db.executeNonQuery(sql);
                    fillDepartmentsjList();
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(DepartmentsGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDepAdd;
    private javax.swing.JList<Item> jListDepartments;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDepName;
    // End of variables declaration//GEN-END:variables
}
